---
- name: "Creates backend app directory"
  file:
    path: ~/udapeople_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: dist.zip
    dest: "~/udapeople_app/dist.zip"

- name: "Install unzip package"
    become: true
    apt:
      name: zip
      state: present
      update_cache: true
    
- name: "Unzip backend files to correct directory"
  shell: |
    sudo apt install unzip
    cd ~/udapeople_app
    rm -rf dist.zip

- name: "Install dependencies for project"
  shell: |
    cd ~/udapeople_app
    npm install

- name: "Executing node"
  shell: |
    export
    pm2 start main.js
  args:
      chdir: /home/ubuntu/udapeople_app/dist
  register: execute_node
  environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
